### ISSUE TITLE
Extract main functions into separate server agnostic package?

### ISSUE THREAD

**Issue by jonaskello** [graphql/express-graphql#559] opened 2019-09-08 08:59 UTC
This package is currently coupled to express but there is a lot of code in here that is not specific to express. If we could split it so the core functions could be made agnostic of what server you are using (express, koa, etc..) then the re-use could probably be better. My thought is that we could have a library of core logic that is mainly pure functions, and then people can compose them into what they need, for example an express middleware, a koa middleware, a server with subscription support etc.

I've made some work towards this, extracting code from this repo, reworking it to server-agnostic part, and then composing it into a koa middleware and it works out quite nicely. The koa specific part is not so large. However now I have code that is not maintained as an "official" package. I could open-source my efforts in a separate package but then it would mean I maintain code that is basically the same as in this repo. Maintaining open source is quite a lot of work and there are usually few resources available so I think it would be better to pool the maintenance resources and create a core package with the core logic. Today there is also a maintained package for [koa](https://github.com/chentsulin/koa-graphql) which I guess has similar code to this package.

**Comment by acao** [comment] 2019-09-08 14:00
this would be great for lambdas/zeit now 2/ FAAS implementations as well

**Comment by jonaskello** [comment] 2019-11-27 12:10
Looks like something similar was suggested in #178.

**Comment by acao** [comment] 2019-12-01 19:03
yes, I think there's one design change we need to make. currently we are setup for connect-based http servers, so express works as does hapi, restify, etc if you see the docs. However, Koa is not connect based. There is `koa-connect` which is not reccomended. So we need a core server module that express-graphql exports, as well as a `koaMiddleware` however we will probably keep it to one package as  @IvanGoncharov and i have discussed, but if folks feel seperate packages are important for particular reasons we can consider that.

So I've set up a project with this as an end goal, showing at least an express and koa reference middleware, and as already, some docs that explain how to use with other connect based http middleware stacks

**Comment by acao** [comment] 2019-12-01 19:04
@jonaskello good point, will call this a dupe of #113 ?

**Closed by acao** 2019-12-01 19:04 UTC
