### ISSUE TITLE
Subscriptions support

### ISSUE THREAD

**Issue by mysterioushunt** [graphql/express-graphql#390] opened 2017-08-30 08:33 UTC
Support GraphQL subscriptions or is there a way to use apollographql/graphql-subscriptions and apollographql/subscriptions-transport-ws with express-graphql?

**Comment by perrosnk** [comment] 2017-09-17 19:56
+1

**Comment by bwoodlt** [comment] 2017-11-12 23:43
+1

**Comment by gauravmakkar** [comment] 2018-01-05 06:34
+1

**Comment by junminstorage** [comment] 2018-03-07 20:12
subscriptions-transport-ws should create a websocket server.  And I figured it out like below by adding subscription operation support in express-graphql's graphiql explorer. 

```
const { execute, subscribe } = require('graphql');
const {createServer} = require('http');
const  { SubscriptionServer } = require('subscriptions-transport-ws');

const PORT = 4000;
const subscriptionsEndpoint = `ws://localhost:${PORT}/subscriptions`;

var app = express();
app.use('/graphql',  graphqlHTTP({
    schema: schema,
    graphiql: true,
    subscriptionsEndpoint: subscriptionsEndpoint
}));

// Create listener server by wrapping express app
const webServer = createServer(app);

webServer.listen(PORT, () => {
    console.log(`GraphQL is now running on http://localhost:${PORT}`);

    // Set up the WebSocket for handling GraphQL subscriptions.
    new SubscriptionServer({
        execute,
        subscribe,
        schema
    }, {
        server: webServer,
        path: '/subscriptions',
    });

});
```

Let me know if this solves the issue and I can create a PR.

**Comment by calvernaz** [comment] 2018-05-07 07:39
@junminstorage this didn't work out for me. I had to plug the module graphql-playground-middleware-express to make it work, but I'm still investing what's the issue tho, given that I'm not sure if the problem is with GraphiQL not triggering the connection.

**Comment by junminstorage** [comment] 2018-05-07 11:09
@calvernaz  thanks for bringing this up. conjunction with above I will need make a PR to expresss-graphql to make it work. 
Let me create PR today.

**Comment by junminstorage** [comment] 2018-05-09 13:56
PR: https://github.com/graphql/express-graphql/pull/436
@calvernaz let me know if it works for you.

**Comment by calvernaz** [comment] 2018-05-10 16:45
Sure @junminstorage, is the fix pinned to any specific version?

**Comment by junminstorage** [comment] 2018-05-10 17:42
I merged the current master to my PR branch. Actually it should work for last release as well which I tested. But if you can help me try it out with latest release and confirm, then we have good confidence to ask @IvanGoncharov to approve it.

**Comment by junminstorage** [comment] 2018-05-14 12:40
Right, the PR is not merged yet and not in any releases. I was meaning the changes in the PR should work for any release greater than v0.6.12 and master too. 
  
For your local test, you need to remove the existing express-graphql in the node_modules/ folder under the nodejs project you are working on, then git clone https://github.com/junminstorage/express-graphql/  , and checkout branch named 'subscription-graphiql-support', then do npm link install this specific project, see doc here: https://docs.npmjs.com/cli/link

Let me know if you still have any problems after doing this. 

I am planning to build a sample project here: https://github.com/junminstorage/graphql-sample, so you may be able to check it out and run it to see how it works. But it will take me some time to do it.

**Comment by calvernaz** [comment] 2018-05-14 19:50
Good news, it worked!! I had to build the dependency first to create the dist folder where the package.json points to the main file, but worked as shown in the image
<img width="1190" alt="screen shot 2018-05-14 at 20 47 28" src="https://user-images.githubusercontent.com/1269712/40019869-675415bc-57b8-11e8-9254-9ed6185fd595.png">

**Comment by junminstorage** [comment] 2018-05-14 19:56
Yep, the source code is typescript. And that is awesome! Thank you! 

@IvanGoncharov can you comment on the PR #436 and so we can move forward on this?

**Comment by IvanGoncharov** [comment] 2018-05-14 20:59
@junminstorage I left a comment in https://github.com/graphql/express-graphql/pull/436#issuecomment-388960292.

**Comment by carlos-cne** [comment] 2018-12-14 11:21
Hi! this PR was commited? I'm trying to do the same thing, but, doesn't worked here...

**Comment by carlos-cne** [comment] 2018-12-14 11:46
> Good news, it worked!! I had to build the dependency first to create the dist folder where the package.json points to the main file, but worked as shown in the image
> <img alt="screen shot 2018-05-14 at 20 47 28" width="1190" src="https://user-images.githubusercontent.com/1269712/40019869-675415bc-57b8-11e8-9254-9ed6185fd595.png">

Hi Calvernaz, can u show me how you builded the dependency at package.json?

**Comment by junminstorage** [comment] 2018-12-14 21:14
just commented here to show my willing to work on this PR if anything we need for it to merge

**Comment by Lcmkey** [comment] 2018-12-25 13:38
> > > Good news, it worked!! I had to build the dependency first to create the dist folder where the package.json points to the main file, but worked as shown in the image
> > > <img alt="screen shot 2018-05-14 at 20 47 28" width="1190" src="https://user-images.githubusercontent.com/1269712/40019869-675415bc-57b8-11e8-9254-9ed6185fd595.png">
> > 
> > 
> > Hi Calvernaz, can u show me how you builded the dependency at package.json?
> 
> Can you check if this works for you? https://github.com/calvernaz/express-graphql
> I stop waiting for the change and creating a version with that fixed.

hello, calvernaz.
can you provide any project sample code for me to reference?
I have study how to subscribe function with "express-graphql" package a few days, but unfortunately.... fail again and again and again......... until now........fail

**Comment by junminstorage** [comment] 2018-12-26 20:08
@Lcmkey, besides you need the code changes like in PR https://github.com/graphql/express-graphql/pull/436 to express-graphql, rebuild the dist/ folder inside,  do you also have the code snippet like below in your server side?

https://github.com/graphql/express-graphql/issues/390#issuecomment-371269023

**Comment by Lcmkey** [comment] 2018-12-28 18:17
@junminstorage 
Thanks for reply. My server side setting exactly like #390 and the request method that is websocket, but it return null instead of listening word "Your subscription data will appear here after server publication!" when i made a  query.
I have updated a simple coding on my github, can you please help for find out the problem or give me some suggestion, thanks.
------------------------------------------------
https://github.com/Lcmkey/draft

**Comment by martinlevesque** [comment] 2019-10-09 20:37
Is there a complete example somewhere ? I have been trying to make subscriptions work with express-graphql and subscriptions-transport-ws with no success.

My server:

```
const express = require('express')
const { createServer } = require('http')
const graphqlHTTP = require('express-graphql')
const { buildSchema, execute, subscribe } = require('graphql')
const  { SubscriptionServer } = require('subscriptions-transport-ws')
const { PubSub } = require('graphql-subscriptions')

const PORT = 4000

const subscriptionsEndpoint = `ws://localhost:${PORT}/subscriptions`;
const pubsub = new PubSub();

// merging schemas:
// https://stackoverflow.com/questions/45911002/can-two-graphqlschema-instances-be-merged

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`

  type MyDocument {
    id: String
    title: String
  }

  type Query {
    retrieveDocument: MyDocument
  }

  type Subscription {
    newDocument: MyDocument
  }
`);

// The root provides a resolver function for each API endpoint
const root = {

  retrieveDocument: () => {

    console.log(`hello`)
    pubsub.publish('NOTIFICATION_NEW_DOCUMENT', { newDocument: {id: "222", title: 'newdocument2' }});

    return {
      id: '111',
      title: 'hello world'
    }
  },

  //Subscription: {
    newDocument: {

      resolve: (arguments) => {
        console.log(`resolving new document`)
        return { 
          id: '112233'
        };
      },


      subscribe: () => {
        console.log(`subscribed...`)
        return pubsub.asyncIterator('NOTIFICATION_NEW_DOCUMENT')
      }
      //  return 
      //}
    }
  //}
  
};

const app = express();

app.use(
  '/graphql',
  graphqlHTTP({
    schema: schema,
    rootValue: root,
    graphiql: true,
    subscriptionsEndpoint
  }),
);

const webServer = createServer(app);

app.listen(PORT, () => {

  // Subscriptions handling:
  new SubscriptionServer({
      execute,
      subscribe,
      schema
  }, {
      server: webServer,
      path: '/subscriptions',
  });

  console.log(`Running a GraphQL API server at http://localhost:${PORT}/graphql`);
});
```

Client:

```

const { SubscriptionClient } = require('subscriptions-transport-ws')
const fetch = require('node-fetch')
const gql = require('graphql-tag')

const { ApolloClient } = require('apollo-client')

const { InMemoryCache } = require('apollo-cache-inmemory')
const { createHttpLink } = require('apollo-link-http');

const ws = require('ws')

const client = new SubscriptionClient('ws://localhost:4000/subscriptions', {
  reconnect: true,
}, ws);

const apolloClient = new ApolloClient({
  link: createHttpLink({ uri: 'http://localhost:4000/graphql', fetch }),
  cache: new InMemoryCache(),
  networkInterface: client,
});

apolloClient.subscribe({
  query: gql`
    subscription newDocumentEventHere {
      newDocument {
        id
      }
    }`,
  variables: {}
}).subscribe({
  next (data) {
    // Notify your application with the new arrived data
    console.log(`oh new data...${JSON.stringify(data)}`)
  }
});

setTimeout(() => {
  apolloClient.query({
    query: gql`
      {
        retrieveDocument {
          id
        }
      }
    `
  }).then((result) => console.log(`res2 ${JSON.stringify(result)}`))
}, 1000)
```

package.json:

```
{
  "name": "subscription-express-graphql",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link-http": "^1.5.16",
    "express": "^4.17.1",
    "express-graphql": "^0.9.0",
    "graphql": "^14.5.8",
    "graphql-subscriptions": "^1.1.0",
    "graphql-tag": "^2.10.1",
    "node-fetch": "^2.6.0",
    "nodemon": "^1.19.3",
    "subscriptions-transport-ws": "^0.9.16"
  }
}

```

**Comment by calvinlarano97** [comment] 2019-10-12 13:18
> Is there a complete example somewhere ? I have been trying to make subscriptions work with express-graphql and subscriptions-transport-ws with no success.
> 
> See below the src, if you see any issue let me know. The subscribe function is never triggered, the client can be run in command line (no browser).
> 
> My server:
> 
> ```
> const express = require('express')
> const { createServer } = require('http')
> const graphqlHTTP = require('express-graphql')
> const { buildSchema, execute, subscribe } = require('graphql')
> const  { SubscriptionServer } = require('subscriptions-transport-ws')
> const { PubSub } = require('graphql-subscriptions')
> 
> const PORT = 4000
> 
> const subscriptionsEndpoint = `ws://localhost:${PORT}/subscriptions`;
> const pubsub = new PubSub();
> 
> // merging schemas:
> // https://stackoverflow.com/questions/45911002/can-two-graphqlschema-instances-be-merged
> 
> // Construct a schema, using GraphQL schema language
> var schema = buildSchema(`
> 
>   type MyDocument {
>     id: String
>     title: String
>   }
> 
>   type Query {
>     retrieveDocument: MyDocument
>   }
> 
>   type Subscription {
>     newDocument: MyDocument
>   }
> `);
> 
> // The root provides a resolver function for each API endpoint
> const root = {
> 
>   retrieveDocument: () => {
> 
>     console.log(`hello`)
>     pubsub.publish('NOTIFICATION_NEW_DOCUMENT', { newDocument: {id: "222", title: 'newdocument2' }});
> 
>     return {
>       id: '111',
>       title: 'hello world'
>     }
>   },
> 
>   //Subscription: {
>     newDocument: {
> 
>       resolve: (arguments) => {
>         console.log(`resolving new document`)
>         return { 
>           id: '112233'
>         };
>       },
> 
> 
>       subscribe: () => {
>         console.log(`subscribed...`)
>         return pubsub.asyncIterator('NOTIFICATION_NEW_DOCUMENT')
>       }
>       //  return 
>       //}
>     }
>   //}
>   
> };
> 
> const app = express();
> 
> app.use(
>   '/graphql',
>   graphqlHTTP({
>     schema: schema,
>     rootValue: root,
>     graphiql: true,
>     subscriptionsEndpoint
>   }),
> );
> 
> const webServer = createServer(app);
> 
> app.listen(PORT, () => {
> 
>   // Subscriptions handling:
>   new SubscriptionServer({
>       execute,
>       subscribe,
>       schema
>   }, {
>       server: webServer,
>       path: '/subscriptions',
>   });
> 
>   console.log(`Running a GraphQL API server at http://localhost:${PORT}/graphql`);
> });
> ```
> 
> Client:
> 
> ```
> 
> const { SubscriptionClient } = require('subscriptions-transport-ws')
> const fetch = require('node-fetch')
> const gql = require('graphql-tag')
> 
> const { ApolloClient } = require('apollo-client')
> 
> const { InMemoryCache } = require('apollo-cache-inmemory')
> const { createHttpLink } = require('apollo-link-http');
> 
> const ws = require('ws')
> 
> const client = new SubscriptionClient('ws://localhost:4000/subscriptions', {
>   reconnect: true,
> }, ws);
> 
> const apolloClient = new ApolloClient({
>   link: createHttpLink({ uri: 'http://localhost:4000/graphql', fetch }),
>   cache: new InMemoryCache(),
>   networkInterface: client,
> });
> 
> apolloClient.subscribe({
>   query: gql`
>     subscription newDocumentEventHere {
>       newDocument {
>         id
>       }
>     }`,
>   variables: {}
> }).subscribe({
>   next (data) {
>     // Notify your application with the new arrived data
>     console.log(`oh new data...${JSON.stringify(data)}`)
>   }
> });
> 
> setTimeout(() => {
>   apolloClient.query({
>     query: gql`
>       {
>         retrieveDocument {
>           id
>         }
>       }
>     `
>   }).then((result) => console.log(`res2 ${JSON.stringify(result)}`))
> }, 1000)
> ```
> 
> package.json:
> 
> ```
> {
>   "name": "subscription-express-graphql",
>   "version": "1.0.0",
>   "description": "",
>   "main": "server.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1",
>     "start": "node server.js"
>   },
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "apollo-cache-inmemory": "^1.6.3",
>     "apollo-client": "^2.6.4",
>     "apollo-link-http": "^1.5.16",
>     "express": "^4.17.1",
>     "express-graphql": "^0.9.0",
>     "graphql": "^14.5.8",
>     "graphql-subscriptions": "^1.1.0",
>     "graphql-tag": "^2.10.1",
>     "node-fetch": "^2.6.0",
>     "nodemon": "^1.19.3",
>     "subscriptions-transport-ws": "^0.9.16"
>   }
> }
> ```

same problem. anyone here could help us.

**Comment by tylerreckart** [comment] 2019-10-12 14:09
@calvinlarano97, @martinlevesque There is currently no support for subscriptions in this package. I integrated this PR into my own package for use in my course on GraphQL, but it should be noted that it was for demonstration purposes only. https://github.com/graphql-in-motion/express-graphql
It is being used here: https://github.com/graphql-in-motion/graphql-news/blob/master/src/server/index.js

I have been following this PR for at this point a few years, and I wouldn't get your hopes up that the maintainers will do anything about it anytime soon. The best option is likely to find another package to build your server.

**Comment by raitucarp** [comment] 2019-10-24 05:15
Is this project even still maintained?

**Comment by junminstorage** [comment] 2019-10-24 12:53
apollo graphql is the most popular platform, lacking support from the facebook for this project, making my PR https://github.com/graphql/express-graphql/pull/436 sitting there for long time.

**Comment by martinlevesque** [comment] 2019-10-24 13:06
@junminstorage the PR works ? The changes look pretty minimal. Let's do it @IvanGoncharov Looks like a significant amount of people needs it (include me). I can do some extra testing or anything else if required.

**Comment by junminstorage** [comment] 2019-10-24 13:29
it works at the time i created the PR, and see comment https://github.com/graphql/express-graphql/issues/390#issuecomment-541328370.  I need to rebase the PR off master, may need additional changes and try it out.

**Comment by IvanGoncharov** [comment] 2019-10-24 21:32
@martinlevesque I already answered it here: https://github.com/graphql/express-graphql/pull/436#issuecomment-388960292
And the situation stays the same. I don't think I'm in power make desigion like this: add vendor-specific protocol into reference GraphQL server hosted under GraphQL foundation.
I'm just one of ~40 people who have commit right to this repo.

But I understand community frustration so to move it forward I will write an email that raises this question with GraphQL Foundation guys. I will keep you posted.

**Comment by junminstorage** [comment] 2019-10-25 00:09
@IvanGoncharov  got your point. Now winter is coming along with holidays, and now I am thinking about raising my sleeves to write my own and replace the subscription client.

**Comment by raitucarp** [comment] 2019-10-25 16:23
Why I bump this feature request? Honestly, I need dynamically reload schema with a subscription feature, express-graphql is easy enough for doing dynamic schema loader.

**Comment by IvanGoncharov** [comment] 2019-11-06 21:49
@martijnwalraven So it seems that the current consensus from GraphQL Foundation is to try to provide some kind of hook/callback that allows you to use different transports for subscriptions including WS transport from Apollo.
It would be great if someone volunteers to experiment with that so we will see if it possible and how much complexity it will add?

**Comment by tylerreckart** [comment] 2019-11-07 00:32
@IvanGoncharov That's something I can look into.

**Comment by junminstorage** [comment] 2019-11-07 01:17
@IvanGoncharov can you elaborate on this? as all of the sample code people provided above,  for the express backend to support the subscription, it is up to application developer to hook up any SubscriptionServer  into express and work with this express-graphql middleware.

the PR is mainly to pass ws endpoint to front-end, https://github.com/graphql/express-graphql/pull/436/files#diff-1fdf421c05c1140f6d71444ea2b27638R207, the moot point or the only place third part library  introduced to demonstrate the subscription capability on the UI is when it is rendered during the development phrase ONLY

**Comment by martinlevesque** [comment] 2019-11-07 01:25
If I understandd correctly (I might be wrong - noob here) the issue previously noted by @IvanGoncharov is with the package subscriptions-transport-ws being added in src/renderGraphiQL.js, not the change in src/index.js (?). 

Perhaps we could add the _src/index.js_ change first to allow people to actually make it work - without subscription support in graphiql and with proper warning ?

**Comment by junminstorage** [comment] 2019-11-07 02:20
nope, see https://github.com/graphql/express-graphql/issues/390#issuecomment-371269023 for example. and please check out the PR linked to this issue.

**Comment by nileio** [comment] 2020-04-07 09:37
looks like this thread is dead .. its April 2020, and looks like its still stagnant for some reason though the change look pretty small.. anyone ?

**Comment by martinlevesque** [comment] 2020-04-08 14:50
Yeah it's kind of disappointing. I would suggest adding a clear comment in the readme stating that there is no support subscriptions, and no plan to add its support.

**Comment by amjedomar** [comment] 2020-05-14 18:37
The community (including me) desperately needs `subscriptions` feature in `express-graphql`

**Comment by acao** [comment] 2020-05-14 18:48
hey folks! i happen to be a maintainer. happy to see what i can do.

ivan has been busy with `graphql` and i’ve been busy with maintaining `graphiql` , graphql playground and the LSP.

sadly this repo has been neglected far more than it should be. if anyone is interested in becoming a maintainer of this repo that would be fantastic. it is widely used still by some very large companies

for now, is it ok if i close this issue and update the docs to note that this does not support subscriptions currently in the readme, and offer some links to alternatives that do?

**Comment by acao** [comment] 2020-05-14 19:03
also if someone wants to open a pull request for this feature, i would be happy to review it! ill try to keep a closer eye out in my github notifications

**Comment by abhijeetsingh-22** [comment] 2020-07-24 15:21
If anyone is still looking for a solution to use subscriptions in express-graphql, I have found a simple way to do this. Have a look at this
[https://youtu.be/r5KY5m5OXsI](https://youtu.be/r5KY5m5OXsI)

**Comment by martinlevesque** [comment] 2020-07-24 15:28
Hey @abhijeetsingh-22 thx will look into it. Would you mind to make a repo/gist with your sample app?

**Comment by abhijeetsingh-22** [comment] 2020-07-24 15:30
> Hey @abhijeetsingh-22 thx will look into it. Would you mind to make a repo/gist with your sample app?
Its a pleasure If I could help
The video description has the link to repo.
Ping me if you have any query

**Comment by martinlevesque** [comment] 2020-07-29 14:45
@abhijeetsingh-22 looked at your example. It works, however you basically have, if I understand correctly, two schemas, one with express-graphql and one on another http server with subscriptionserver, and the types basically need to be duplicated in both schemas. Is there a way to share types between two schemas (made an issue here https://github.com/abhijeetsingh-22/Realtime-Chat-App/issues/1 )? If not it's not so much maintainable from my opinion, and not so clean, as typically you subscribe to the same types you query/mutate.

**Comment by abhijeetsingh-22** [comment] 2020-07-29 14:59
@martinlevesque sure I will look into this issue. Currently I am little busy. I will update in 2-3 days

**Comment by martinlevesque** [comment] 2020-07-30 13:22
works well with these 2 changes https://github.com/abhijeetsingh-22/Realtime-Chat-App/issues/2 and https://github.com/abhijeetsingh-22/Realtime-Chat-App/issues/1

Will have to check if it works with graphiql (I guess not?).
After checking this I would suggest to point a link to this sample (or include the sample example in "examples"), as it allows to have working subscriptions with express-graphql.

**Comment by junminstorage** [comment] 2020-08-11 15:45
The PR for this is created https://github.com/graphql/express-graphql/pull/687. It contains a link to tutorial project showing how it is done for subscription and web socket integration.

**Comment by Hongbo-Miao** [comment] 2020-10-10 17:07
[graphql-transport-ws](https://github.com/enisdenjo/graphql-transport-ws) is also a very good library to provide GraphQL subscription.

Here are the codes that I have succeed:

**Server (GraphQL Schema Definition Language)**

```js
    import { createServer } from 'graphql-transport-ws';
    import { buildSchema } from 'graphql';

    const schema = buildSchema(`
      type Subscription {
        greeting: String
      }
    `);
    
    const roots = {
      subscription: {
        greeting: async function* sayHiIn5Languages() {
          for (const hi of ['Hi', 'Bonjour', 'Hola', 'Ciao', 'Zdravo']) {
            yield { greeting: hi };
          }
        },
      },
    };
    
    createServer(
      {
        schema,
        execute,
        subscribe,
        roots,
      },
      {
        server, // Your HTTP server
        path: '/graphql',
      }
    );
```

**Server (GraphQL.js GraphQLSchema object way)**

```js
    import { execute, subscribe, GraphQLObjectType, GraphQLSchema, GraphQLString } from 'graphql';
    import { createServer } from 'graphql-transport-ws';
    import { PubSub } from 'graphql-subscriptions';
    
    const pubsub = new PubSub();
    
    const subscription = new GraphQLObjectType({
      name: 'Subscription',
      fields: {
        greeting: {
          type: GraphQLString,
          resolve: (source) => {
            if (source instanceof Error) {
              throw source;
            }
            return source.greeting;
          },
          subscribe: () => {
            return pubsub.asyncIterator('greeting');
          },
        },
      },
    });
    
    const schema = new GraphQLSchema({
      query,
      mutation,
      subscription,
    });
    
    setInterval(() => {
      pubsub.publish('greeting', {
        greeting: 'Bonjour',
      });
    }, 1000);
    
    createServer(
      {
        schema,
        execute,
        subscribe,
      },
      {
        server, // Your HTTP server
        path: '/graphql',
      }
    );
```

**Client**

```js
    import { createClient } from 'graphql-transport-ws';

    const client = createClient({
      url: 'wss://localhost:5000/graphql',
    });
    
    client.subscribe(
      {
        query: 'subscription { greeting }',
      },
      {
        next: (data) => {
          console.log('data', data);
        },
        error: (error) => {
          console.error('error', error);
        },
        complete: () => {
          console.log('no more greetings');
        },
      }
    );
```

*DISCLOSE: I am not associated with the library.*

**Comment by joshbedo** [comment] 2021-01-03 01:05
Whats the status on this? Would love to be able to use subscriptions for a messaging feature I have.

**Comment by acao** [comment] 2021-01-03 15:13
oops forgot to close this ticket! juggling so many efforts in my free time 🥵 . it's very important to note that `express-graphql` has *always* supported subscriptions, it's just a matter of configuration. for example, graphql-ws has had a [config example](https://github.com/enisdenjo/graphql-ws#express) for some time. 

we have started with [updating the docs](https://github.com/graphql/express-graphql#setup-with-subscription-support) to show how to add subscriptions support using `graphql-transport-ws`.  

also in @#687 we updated graphiql to work with subscriptions, but just with `graphql-transport-ws` for now.

we will follow up with a PR and documentation on how to add `graphql-ws`, which implements the transport specification that will replace `graphql-transport-ws`, as `graphql-transport-ws` is being retired as you can probably see in the project readme. to note, we are working with maintainers of *both* of these projects already.

And for now, I will close this ticket since we have documented this!

If anyone wants to see additional features added to improve the subscriptions documentation or have any other issues, feel free to open a new one!

**Closed by acao** 2021-01-03 15:13 UTC

**Comment by joshbedo** [comment] 2021-01-05 18:17
Yeah more documentation would be great! its not super clear on how the setup works.
