### ISSUE TITLE
Unmet Peer version, need to update supported dependencies

### ISSUE THREAD

**Issue by SiNONiMiTY** [graphql/express-graphql#807] opened 2022-07-09 02:34 UTC
When installing graphql and express-graphql, I am encountering this error

unmet peer graphql@"^14.7.0 || ^15.3.0": found 16.5.0

Please update the packages to support the latest version of dependencies

**Comment by adam-nielsen** [comment] 2022-08-20 06:06
Duplicate of #790 and #805

**Comment by riosje** [comment] 2022-08-26 19:49
@adam-nielsen do you know if this project is going to be deprecated?

**Comment by adam-nielsen** [comment] 2022-08-29 00:29
No idea.  I tried e-mailing the GraphQL contact address to ask if anyone was looking at this project as it seems to have become abandoned, but I haven't received a response.

Maybe someone should log an issue on the GraphQL documentation site to ask whether the express-graphql stuff should be removed, given that it is no longer being maintained?

**Comment by riosje** [comment] 2022-08-29 01:28
I just created for them a ticket in the linux foundation Jira.
Don't know if that ticket is going to be reviewed by some one.
https://jira.linuxfoundation.org/plugins/servlet/theme/portal/26/RR-4

Thank you @adam-nielsen for taking the time to answer me.

**Comment by riosje** [comment] 2022-08-29 01:36
I have created an issue in the Linux Foundation Jira https://jira.linuxfoundation.org/plugins/servlet/theme/portal/26/RR-4, but I don't know if it is enough.
@IvanGoncharov @leebyron @wincent @chentsulin  @danielrearden guys I can see you're active contributors, could you take a look on this?
The thing here is that, there is a bunch of projects which have this package as dependency, so there should be thousands of projects with this dependency issue, I just land here because of this issue in 3 different non-related projects, so I can't imagine the amount of projects with this issue.

**Comment by BlueSialia** [comment] 2022-10-06 12:00
For those interested, I forked the project at https://github.com/BlueSialia/express-graphql to solve this and some other issues I was having.

The company I work at uses it for a project, so I will be maintaining it for a long while.

Be aware that I made some changes already to the library, so just replacing `express-graphql` with `@bluesialia/express-graphql` may not be enough in some cases.

**Comment by newbeb** [comment] 2022-11-07 13:44
FYI, Looks like they are deprecating express-graphql in favor of graphql-http: https://github.com/graphql/express-graphql/pull/816.

#790 #805

**Comment by amerikan** [comment] 2022-12-19 20:40
From the various graphql servers alternatives, in our experience the easiest one to migrate over to, almost a drop in replacement, was [GraphQL Yoga](https://www.the-guild.dev/graphql/yoga-server) with their [Express integration](https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-express).

**Comment by saihaj** [comment] 2022-12-26 20:38
This project is deprecated and we recommend to moving to alternatives. You can read more here https://github.com/graphql/express-graphql#this-library-is-deprecated

**Closed by saihaj** 2022-12-26 20:38 UTC
