### ISSUE TITLE
Use for Restify requires not stringifying json

### ISSUE THREAD

**Issue by terencechow** [graphql/express-graphql#216] opened 2017-02-14 10:21 UTC
I'm not sure what [this line](https://github.com/graphql/express-graphql/blob/master/src/index.js#L323) is doing but it makes this repo not compatible with Restify since the response is returned as a stringified JSON. Note that in Express 4.x you don't need to stringify the JSON either. 

For reference here the line that is causing problems is 

`var_payload = JSON.stringify(result, null, pretty? 2:0)`: 

in the follow code:
```
 // Otherwise, present JSON directly.
        var _payload = JSON.stringify(result, null, pretty ? 2 : 0);
        response.setHeader('Content-Type', 'application/json; charset=utf-8');
        sendResponse(response, result);
```

Is this line for compatibility of an older Express? If not can we remove it so that this repo can be used with Restify? I can make a PR if you want.

**Comment by asiandrummer** [comment] 2017-02-23 19:08
> Is this line for compatibility of an older Express?

Not sure what the exact intention at the time was, but since we're @ Express 4.x anyways I think we can go ahead and do that. cc @leebyron though.

**Comment by santino** [comment] 2017-04-07 07:55
Any update on this?
I'm facing the same issue using express-graphql with restify.

Basically this block of code
```
  // Otherwise, present JSON directly.
  const payload = JSON.stringify(result, null, pretty ? 2 : 0);
  response.setHeader('Content-Type', 'application/json; charset=utf-8');
  sendResponse(response, payload);
```

Could just be simplified into this:
```
  // const payload = JSON.stringify(result, null, pretty ? 2 : 0);
  response.setHeader('Content-Type', 'application/json; charset=utf-8');
  sendResponse(response, result);
```

This is causing the response to be stringified twice which is breaking the implementation with a Relay client app.

It would be good to know what the plan is to tackle this issue.

**Comment by wincent** [comment] 2017-04-07 17:18
I think we'd accept a PR on this. If this requires Express >= 4 then we might want to add that as a peer dependency. Currently it's only a dev dependency.

**Comment by santino** [comment] 2017-04-07 20:05
I'm looking into making a PR for this.
It's not as straightforward as it might seem if you want to stay compatible with all your current features.

First of all if we delegate responsibility of stringifying JSON to the server you will lose the 'pretty'  printing option.
Also compatibility with Connect might be an issue as I don't believe they stringify the response by default like express and restify, and they don't have a json function on their response method (`res.json({foo: 'bar'})`).

That's just my first few discoveries.

**Comment by wincent** [comment] 2017-04-07 21:21
> That's just my first few discoveries.

Thanks for sharing your research!

**Comment by santino** [comment] 2017-04-09 20:59
I have now opened a pull request, see #272

This will add full compatibility with Restify by removing the double stringification and also making GraphiQL work.
It doesn't break any existing compatibility: Express 4, 3 and Connect will still work exactly as before.

The only breaking change is that we will loose the 'pretty' option, as mentioned, since the server will be responsible for the stringification; which I believe is not really an issue as any tool that developers use to monitor API responses (including GraphiQL) already provides pretty printing of JSON responses.

I hope you guys will approve and make a new release soon as I tested this code with my restify server and it would be great to just be able to install a new version of `express-graphql` from npm.

**Comment by santino** [comment] 2017-05-05 20:45
Hi guys, sorry to bump on this.
I didn't want to push it so far as I understand you're busy, but a considerable amount of time has now passed and I was wondering what your plans are with my PR to add compatibility with Restify which I believe would be greatly appreciated by many developers.

**Comment by wincent** [comment] 2017-05-05 23:12
Thanks for the reminder, @santino. We're not actually so busy that we forgot about your PR: it's actually that with a change like this I wanted to give time for others to comment on it. Want to give it a rebase on top of current `master` and we'll give it a formal review?

**Comment by santino** [comment] 2017-05-06 23:19
Hi @wincent, I surely understand.
The change is big, but as I mentioned the only break is the drop of the 'pretty' option which I truly believe is not a big deal as mentioned already.
I have now rebased onto `master`; looking forward to finalise my contribution to this project.

**Comment by santino** [comment] 2017-05-16 07:55
I can confirm that the new version `0.6.5` of `express-graphql` released yesterday brings compatibility with Restify, hence this issue can now be closed.

**Comment by wincent** [comment] 2017-05-16 17:46
Ha, I saw it go in, then I saw it get reverted. I didn't see that it got re-merged though. Great.

**Closed by wincent** 2017-05-16 17:46 UTC
