### ISSUE TITLE
Syntax Error with express-graphql

### ISSUE THREAD

**Issue by sumitsssss** [graphql/express-graphql#665] opened 2020-07-05 14:58 UTC
Here I am trying to creating Graphql Schema
Code=>

 
`const express = require('express');

const graphqlHttp = require("express-graphql")
const { buildSchema } = require('graphql');

const app = express();

app.use(express.json());

app.use(
  '/graphql',
  graphqlHttp({
    schema: buildSchema(`
        type RootQuery {
            events: [String!]!
        }

        type RootMutation {
            createEvent(name: String): String
        }

        schema {
            query: RootQuery
            mutation: RootMutation
        }
    `),
    rootValue: {
      events: () => {
        return ['Cooking', 'Sailing', 'All-Night Coding'];
      },
      createEvent: (args) => {
        const eventName = args.name;
        return eventName;
      }
    },
    graphiql: true
  })
);

app.listen(3000, ()=>console.log("Server up and running at Port 3000"));`

but I am getting error of 

      pretty = optionsData.pretty ?? false;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\Desktop\Graphql-FullStack\index.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

I installed express-graphql of version 0.1.0.

Now what should I do??

**Comment by danielrearden** [comment] 2020-07-05 15:03
@sumitsssss Thanks for submitting this issue. This looks like a regression on our end. We'll get it patched ASAP.

**Comment by IvanGoncharov** [comment] 2020-07-05 15:16
Fixed in `0.10.1` 📦

**Closed by IvanGoncharov** 2020-07-05 15:16 UTC
Labels: bug
